# Generated by Django 4.1.7 on 2023-03-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
                ('image', models.FileField(upload_to='')),
                ('license_image', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=1000)),
                ('lattitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.login')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('Date', models.DateField(max_length=200)),
                ('image', models.ImageField(max_length=200, upload_to='')),
                ('rating1', models.CharField(max_length=100)),
                ('rating2', models.CharField(max_length=100)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.restaurant')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.user')),
            ],
        ),
        migrations.CreateModel(
            name='food_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('portion', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.food_type')),
            ],
        ),
        migrations.CreateModel(
            name='feeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=100)),
                ('feed', models.CharField(max_length=200)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.user')),
            ],
        ),
        migrations.CreateModel(
            name='facility_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('Date', models.DateField(max_length=200)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.restaurant')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.user')),
            ],
        ),
    ]
