# Generated by Django 4.1.7 on 2023-03-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='category',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_item',
            name='special_dishes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
