# Generated by Django 4.1.7 on 2023-03-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_alter_food_type_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item',
            name='special_dishes',
        ),
    ]
