# Generated by Django 4.1.7 on 2023-03-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_remove_food_item_special_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
