# Generated by Django 4.1.7 on 2023-03-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_alter_food_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='time1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time2',
            field=models.CharField(max_length=100),
        ),
    ]
