# Generated by Django 4.1.7 on 2023-03-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0007_alter_feeback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeback',
            name='Date',
            field=models.CharField(max_length=200),
        ),
    ]
