# Generated by Django 4.1.7 on 2023-03-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0008_alter_feeback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item',
            name='portion',
        ),
    ]
