# Generated by Django 4.1.7 on 2023-03-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_remove_food_item_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='item',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food_type',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
