# Generated by Django 4.1.7 on 2023-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0010_alter_food_item_item_alter_food_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food_type',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
