# Generated by Django 4.1.7 on 2023-03-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_alter_food_item_item_alter_food_type_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food_item',
            unique_together={('type_id', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='food_type',
            unique_together={('rest_id', 'type')},
        ),
    ]
